server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: false

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/master-changelog.xml